import { readFile, writeFile, mkdir, readdir, rm, copyFile, cp, stat } from 'node:fs/promises';
import { marked } from 'marked';
import { parse } from 'yaml';
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const posts = [];
for (const file of await readdir('content')) {
  if (!file.endsWith('.md')) continue;
  const source = await readFile(`content/${file}`, 'utf8');
  const match = source.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) throw Error(`${file}: missing front matter`);
  const data = parse(match[1]);
  if (data.draft) continue;
  const slug = file.slice(0,-3);
  if (!/^[a-z0-9-]+$/.test(slug)) throw Error(`${file}: use a lowercase, hyphenated filename`);
  if (!data.title || !/^\d{4}-\d{2}-\d{2}$/.test(data.date) || !Number.isFinite(Date.parse(data.date)) || !['writing','project'].includes(data.type) || !Array.isArray(data.categories) || data.categories.some(c=>typeof c!=='string')) throw Error(`${file}: invalid title, date, type, or categories`);
  posts.push({...data, slug, body: marked.parse(match[2]), minutes: Math.max(1,Math.ceil(match[2].split(/\s+/).length/220))});
}
posts.sort((a,b)=>b.date.localeCompare(a.date));
const categories = [...new Set(posts.flatMap(p=>p.categories))].sort();
const date = d => new Date(d+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'});
const meta = p => `<span>${p.type==='project'?'Project notes':'Writing'}</span><span>${date(p.date)}</span><span>${p.minutes} min read</span>`;
const shell = (title, description, body, home=false) => `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#f5f4ee"><title>${esc(title)}${home?'':' — Alla Spears'}</title><link rel="stylesheet" href="/style/index.css"><link rel="icon" href="/favicon.svg" type="image/svg+xml"></head>
<body><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="identity" href="/" aria-label="Alla Spears home"><span class="identity-mark">a<span><svg class="arrow-icon" viewBox="0 0 16 16" aria-hidden="true"><path d="M3 13 13 3M3 3h10v10" fill="none" stroke="currentColor" stroke-width="1.2"/></svg></span></span>Alla Spears<span class="identity-dot">.</span></a><nav aria-label="Main navigation"><a href="/#archive" ${home?'aria-current="page"':''}>The index</a><a href="/#about">About</a><a class="contact-link" href="mailto:apolisskaya@gmail.com">Say hello <span><svg class="arrow-icon" viewBox="0 0 16 16" aria-hidden="true"><path d="M3 13 13 3M3 3h10v10" fill="none" stroke="currentColor" stroke-width="1.2"/></svg></span></a></nav></header>
${body}<footer><span>© ${new Date().getFullYear()} Alla Spears</span><span class="footer-note">A small site. Too many tabs.</span><a href="#top">Back to top ↑</a></footer><script src="/scripts/site.js" defer></script></body></html>`;
const cards = posts.map((p,i)=>`<article class="entry" data-type="${p.type}" data-categories="${esc(JSON.stringify(p.categories))}" data-search="${esc([p.title,p.description,...p.categories].join(' ').toLowerCase())}"><span class="entry-number">${String(i+1).padStart(2,'0')}</span><div class="entry-content"><div class="entry-meta">${meta(p)}</div><h3><a href="/posts/${p.slug}/">${esc(p.title)} <span class="entry-arrow"><svg class="arrow-icon" viewBox="0 0 16 16" aria-hidden="true"><path d="M3 13 13 3M3 3h10v10" fill="none" stroke="currentColor" stroke-width="1.2"/></svg></span></a></h3><p>${esc(p.description||'')}</p><div class="tags">${p.categories.map(c=>`<span>${esc(c)}</span>`).join('')}</div></div></article>`).join('');
const home = `<main id="main"><section class="hero" id="top"><div class="hero-copy"><div class="eyebrow"><span class="status-dot"></span> A PERSONAL CORNER OF THE INTERNET</div><h1>Good questions.<br>Interesting rabbit holes<span class="sage">.</span></h1><p class="intro">I’m Alla. This is where I think out loud, document things I’m making, and follow an idea a little further than strictly necessary.</p><a class="text-link" href="#archive">Explore the notebook <span>↓</span></a></div><div class="orbit-art" aria-hidden="true"><span class="art-axis"></span><span class="orbit orbit-one"></span><span class="orbit orbit-two"></span><span class="orbit orbit-three"></span><span class="art-core">*</span><span class="art-star">+</span><span class="art-label">FIG. 01 / A CURIOUS MIND</span></div></section><div class="margin-note"><span>THINKING / MAKING / OCCASIONALLY TOUCHING GRASS</span><span>Stay curious. Get a little weird. ↘</span></div>
<section class="archive" id="archive"><div class="section-heading"><div><span class="eyebrow">THE NOTEBOOK</span><h2>A few things, written down.</h2></div><span class="count">${posts.length} ${posts.length===1?'entry':'entries'} & counting</span></div><div class="archive-controls"><div class="type-filters" role="group" aria-label="Filter by type"><button class="active" data-type-filter="all" aria-pressed="true">Everything</button><button data-type-filter="writing" aria-pressed="false">Writing</button><button data-type-filter="project" aria-pressed="false">Projects</button></div><div class="search-controls"><label class="sr-only" for="category">Category</label><select id="category"><option value="all">All categories</option>${categories.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('')}</select><label class="search"><span aria-hidden="true">⌕</span><input id="search" type="search" placeholder="Find a rabbit hole…" aria-label="Search entries"></label></div></div><div class="entries">${cards}</div><p id="empty" hidden>No entries here yet. Try another filter.</p><p class="filter-status sr-only" role="status" aria-live="polite"></p></section>
<section class="about" id="about"><div><span class="eyebrow">THE PERSON BEHIND THE TABS</span><h2>Serious about the work.<br>A little unserious about everything else.</h2></div><div><p>I like useful things, thoughtful writing, and questions that don’t fit neatly into a search bar. This space is a growing collection of notes, experiments, and things worth sharing.</p><p class="aside">Less personal brand. More personal notebook.</p><div class="social-links"><a href="https://github.com/apolisskaya">GitHub <svg class="arrow-icon" viewBox="0 0 16 16" aria-hidden="true"><path d="M3 13 13 3M3 3h10v10" fill="none" stroke="currentColor" stroke-width="1.2"/></svg></a><a href="https://www.linkedin.com/in/alla-spears-05536a99/">LinkedIn <svg class="arrow-icon" viewBox="0 0 16 16" aria-hidden="true"><path d="M3 13 13 3M3 3h10v10" fill="none" stroke="currentColor" stroke-width="1.2"/></svg></a><a href="mailto:apolisskaya@gmail.com">Email <svg class="arrow-icon" viewBox="0 0 16 16" aria-hidden="true"><path d="M3 13 13 3M3 3h10v10" fill="none" stroke="currentColor" stroke-width="1.2"/></svg></a></div></div></section></main>`;
await rm('dist',{recursive:true,force:true});
await mkdir('dist/style',{recursive:true});await mkdir('dist/scripts',{recursive:true});
await copyFile('style/index.css','dist/style/index.css');await copyFile('scripts/site.js','dist/scripts/site.js');await copyFile('favicon.svg','dist/favicon.svg');
if (await stat('public').then(s=>s.isDirectory()).catch(()=>false)) await cp('public','dist',{recursive:true});
await writeFile('dist/index.html',shell('Alla Spears — a personal notebook','Writing, project notes, and interesting rabbit holes. A personal notebook by Alla Spears.',home,true));
for (const p of posts) {
 await mkdir(`dist/posts/${p.slug}`,{recursive:true});
 await writeFile(`dist/posts/${p.slug}/index.html`,shell(p.title,p.description||p.title,`<main id="main" class="post" ><a class="back-link" id="top" href="/#archive">← Back to the notebook</a><header class="post-header"><div class="entry-meta">${meta(p)}</div><h1>${esc(p.title)}</h1><p class="post-description">${esc(p.description||'')}</p><div class="tags">${p.categories.map(c=>`<span>${esc(c)}</span>`).join('')}</div></header><article class="prose">${p.body}</article><div class="post-end"><span>End of this rabbit hole.</span><a href="/#archive">Find another →</a></div></main>`));
}
await writeFile('dist/404.html',shell('Page not found','This page could not be found.',`<main id="main" class="post"><div id="top"></div><span class="eyebrow">404 / LOST IN THE TABS</span><h1>A small detour.</h1><p>This page doesn’t exist, or it’s moved.</p><a class="text-link" href="/">Back to the notebook →</a></main>`));
console.log(`Built ${posts.length} entries with ${categories.length} categories into dist/`);
